### ISSUE TITLE
The class distribution of imbalanced datasets

### ISSUE THREAD

**Issue by chester256** [PrateekMunjal/TorchAL#1]
Thanks for your incredible work. The classes seem unbalanced for the initial labeled set while still balanced for the unlabeled set. The class distributions of `data_indexes/CIFAR10/imbalanced/partition_1/lSet_CIFAR10.npy`  and `uSet_CIFAR10.npy` are shown below. 
To me, the class distribution of lSet and USet should be similar as they are drawn from the same distribution, e.g., both of them follow a long-tail distribution. 

<img width="644" alt="image" src="https://user-images.githubusercontent.com/18751402/177709645-5d536ca5-4818-451c-8baf-2dde1643ba95.png">

**Comment by PrateekMunjal** [comment]
Hi @chester256, thanks for your interest in our work. 

The class distribution seems unbalanced for labelled sets because we simulated to formulate a setting where it is easy to get images for one label but very tough for some other label, and thus the class distribution follows a long tail. Also in our work we always assumed that we will access labels only for labelled sets. As in the real world, we have no access to labels for the unlabeled sets, therefore both balanced and unbalanced class distribution scenarios are possible. And it was just a setting that in our work we tried with the first case only. Therefore, it is surely worth experimenting to try out the second scenario. Thanks for your great observation.
